/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiLlmRouteImport } from './routes/api/llm'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'
import { Route as ApiExtractDocumentTextRouteImport } from './routes/api/extract-document-text'
import { Route as ApiArchiveImageRouteImport } from './routes/api/archive-image'
import { Route as ApiArchiveFeedbackRouteImport } from './routes/api/archive-feedback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLlmRoute = ApiLlmRouteImport.update({
  id: '/api/llm',
  path: '/api/llm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtractDocumentTextRoute = ApiExtractDocumentTextRouteImport.update({
  id: '/api/extract-document-text',
  path: '/api/extract-document-text',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArchiveImageRoute = ApiArchiveImageRouteImport.update({
  id: '/api/archive-image',
  path: '/api/archive-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArchiveFeedbackRoute = ApiArchiveFeedbackRouteImport.update({
  id: '/api/archive-feedback',
  path: '/api/archive-feedback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/archive-feedback': typeof ApiArchiveFeedbackRoute
  '/api/archive-image': typeof ApiArchiveImageRoute
  '/api/extract-document-text': typeof ApiExtractDocumentTextRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/llm': typeof ApiLlmRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/archive-feedback': typeof ApiArchiveFeedbackRoute
  '/api/archive-image': typeof ApiArchiveImageRoute
  '/api/extract-document-text': typeof ApiExtractDocumentTextRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/llm': typeof ApiLlmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/archive-feedback': typeof ApiArchiveFeedbackRoute
  '/api/archive-image': typeof ApiArchiveImageRoute
  '/api/extract-document-text': typeof ApiExtractDocumentTextRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/llm': typeof ApiLlmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/archive-feedback'
    | '/api/archive-image'
    | '/api/extract-document-text'
    | '/api/generate-image'
    | '/api/llm'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/archive-feedback'
    | '/api/archive-image'
    | '/api/extract-document-text'
    | '/api/generate-image'
    | '/api/llm'
  id:
    | '__root__'
    | '/'
    | '/api/archive-feedback'
    | '/api/archive-image'
    | '/api/extract-document-text'
    | '/api/generate-image'
    | '/api/llm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiArchiveFeedbackRoute: typeof ApiArchiveFeedbackRoute
  ApiArchiveImageRoute: typeof ApiArchiveImageRoute
  ApiExtractDocumentTextRoute: typeof ApiExtractDocumentTextRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
  ApiLlmRoute: typeof ApiLlmRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/llm': {
      id: '/api/llm'
      path: '/api/llm'
      fullPath: '/api/llm'
      preLoaderRoute: typeof ApiLlmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extract-document-text': {
      id: '/api/extract-document-text'
      path: '/api/extract-document-text'
      fullPath: '/api/extract-document-text'
      preLoaderRoute: typeof ApiExtractDocumentTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/archive-image': {
      id: '/api/archive-image'
      path: '/api/archive-image'
      fullPath: '/api/archive-image'
      preLoaderRoute: typeof ApiArchiveImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/archive-feedback': {
      id: '/api/archive-feedback'
      path: '/api/archive-feedback'
      fullPath: '/api/archive-feedback'
      preLoaderRoute: typeof ApiArchiveFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiArchiveFeedbackRoute: ApiArchiveFeedbackRoute,
  ApiArchiveImageRoute: ApiArchiveImageRoute,
  ApiExtractDocumentTextRoute: ApiExtractDocumentTextRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
  ApiLlmRoute: ApiLlmRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
